start_time, end_time = input().split()
sh, sm = map(int, start_time.split(":"))
eh, em = map(int, end_time.split(":"))
total_min = (eh * 60 + em) - (sh * 60 + sm)
h, m = divmod(total_min, 60)
print(f"Total Minutes: {total_min} | Duration: {h}h {m}m")
